### ISSUE TITLE
Contributors file

### ISSUE THREAD

**Issue by gregv12** [v12technology/fluxtion#1]
Create a contributors file:
We want people to join in, so need to make this clear and simple entry point.

Need to have a copyright assignment process that works for contributors.

**Comment by Decat-SimonA** [comment]
Hello, 

Fluxtion looks really **amazing** but it is really confusing for newcomers.

http://fluxtion.com seems to indicate we need to install a `.exe`/`.sh` and activate it with a key. The [quickstart](https://github.com/v12technology/fluxtion-quickstart) mentions this too in its `pom.xml`
```xml
        <!--
        replace this property with the value of your install or run:
        mvn install -Dfluxtion.exe.path=[path to fluxtion executable]
        -->
        <fluxtion.exe.path>c:\Program Files\V12\fluxtion-declarative-extended-trial-0.1.16\fluxtion.exe</fluxtion.exe.path>
```
but it doesn't seems to be used 🤔 

Is the website fluxtion.com obsolete ? Is the trial not needed anymore an everything has been open sourced ?

I found multiple dead links on the gitbook but I cannot find the repository: can you link me to it  ? I'll be glad to fix those typo/mistake

**Comment by gregv12** [comment]
Hi Simon,

Thanks for the really positive comments. Sorry for not replying sooner I was travelling. I agree the welcome/get started path is confusing for newcomers and any help is gratefully received!! 

**Fluxtion background:**

- I open sourced Fluxtion at the beginning of the year.
- All functionality is pure java, no keys or .exe files are required
- The documents on github do not reflect the change in status. Particularly examples and quickstart
- The fluxtion.com website is live, but out of date wrt to open source status

I have not run an open source project before so I am feeling my way with this, please bear with me :)

**Gitbook/help** 

I originally pointed github to my personal repo, there should be an edit on github button on each page now. I will move the gitbook repo to fluxtion github. I am not experienced with collaborating on gitbook via github, but happy to accept any help you are willing to give.

I have started working on the quickstart examples here: https://github.com/gregv12/articles/tree/master/2019/may/quickstart/src/main/java/com/fluxtion/articles/quickstart

**Next steps**

- update the https://github.com/v12technology/fluxtion-examples readme to remove references to closed source instructions
- delete fluxtion-examples that are now included in core fluxtion repo under examples folder
- rewrite quick start examples to use open source implementation
- write a helloworld/quick start blog and publish on dzone/java code geeks hopefully.
- move gotbook doc repo to fluxtion github account.
- Add issues to track the this work.
