### ISSUE TITLE
Compiler does not work with Java 12

### ISSUE THREAD

**Issue by gregv12** [v12technology/fluxtion#30]
The fluxtion compiler does not work with Java 12. Fluxtion uses the compiler from chronicle which uses deprecated api's in Java 11, that are removed in Java 12.

To repeat run Fluxtion build in Java 12.

Need a solution with custom class loader and source to Java compiler. Ideally should work as part of the Java Module System.

**Comment by Allsimon** [comment]
Do you have any idea where to look for this ? 🤔

**Comment by gregv12** [comment]
I have fixed this. Embedded the openhft runtime compiler library and subclassed a classloader and then removed all the illegal calls that caused Java 12 to fail
